use_default_settings: true

server:
  bind_address: "0.0.0.0"
  port: 8888
  base_url: "https://onrender.com"
  secret_key: "ein_sicheres_passwort_hier"

http:
  x_forwarded_for: true

engines:
  - name: ahmia
    remove: true
  - name: torch
    remove: true
